[package]
name = "httpServer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
[dependencies.windows]
version = "0.58.0"
features = ["Win32_Foundation","Win32_System_Threading","Win32_System_Memory","Win32_System_Diagnostics","Win32_System_Diagnostics_Debug","Win32_System_LibraryLoader","Win32_Security","Win32_UI","Win32_UI_WindowsAndMessaging"]


